version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: InduMine
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./data/indumine_db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - indumine-network

  backend:
    build: ./backend
    container_name: indumine-api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    networks:
      - indumine-network

  frontend:
    build: ./front-end
    container_name: indumine-ui
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - indumine-network

networks:
  indumine-network:
    driver: bridge

volumes:
  mysql_data: